#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// Full Duplex I2S: MAX98357A and INMP441 share BCLK and WS on ESP32-C3
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_7
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_3
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_6  // MAX98357A DIN
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_10 // INMP441 SD

// OLED SSD1306 0.96" I2C Pins
#define DISPLAY_SDA_PIN     GPIO_NUM_4
#define DISPLAY_SCL_PIN     GPIO_NUM_5

// Touch sensor TTP223 / BOOT button
#define BOOT_BUTTON_GPIO    GPIO_NUM_0

#define BUILTIN_LED_GPIO    GPIO_NUM_8

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#endif // _BOARD_CONFIG_H_
