#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// Full Duplex I2S Pins (MAX98357A + INMP441)
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_1
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_0  // MAX98357A DIN
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_3  // INMP441 SD

// OLED SSD1306 0.96" I2C Pins
#define DISPLAY_SDA_PIN     GPIO_NUM_7
#define DISPLAY_SCL_PIN     GPIO_NUM_6

#define BUILTIN_LED_GPIO    GPIO_NUM_8
#define BOOT_BUTTON_GPIO    GPIO_NUM_9  // Touch TTP223 / BOOT

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#endif // _BOARD_CONFIG_H_
