#ifndef DASAIMOCHI_FRAMES_H
#define DASAIMOCHI_FRAMES_H

#include <cstdint>

#define DASAIMOCHI_TOTAL_IDLE_FRAMES 772
#define DASAIMOCHI_FRAME_WIDTH 128
#define DASAIMOCHI_FRAME_HEIGHT 64
#define DASAIMOCHI_FRAME_SIZE 1024

extern const uint8_t g_dasaimochi_frames[DASAIMOCHI_TOTAL_IDLE_FRAMES][DASAIMOCHI_FRAME_SIZE];

#endif // DASAIMOCHI_FRAMES_H
